import { execFile } from "node:child_process";
import { access, mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";

import { afterEach, describe, expect, it } from "vitest";

import {
  applyStandardDocumentationScaffold,
  planStandardDocumentationScaffold,
  STANDARD_DOCUMENTATION_TEMPLATE_VERSION,
} from "../../src/framework/documentation-scaffold.js";
import { loadProjectManifest } from "../../src/framework/project-manifest.js";

const execFileAsync = promisify(execFile);
const fixtures: string[] = [];

afterEach(async () => {
  await Promise.all(fixtures.splice(0).map((fixture) => rm(fixture, { recursive: true, force: true })));
});

describe("standard documentation scaffold", () => {
  it("plans without writing, applies once, validates, and repeats idempotently", async () => {
    const root = await gitFixture("blank-project");
    const planned = await planStandardDocumentationScaffold(root, { projectId: "blank-project" });
    expect(planned.templateVersion).toBe(STANDARD_DOCUMENTATION_TEMPLATE_VERSION);
    expect(planned.conflicts).toEqual([]);
    expect(planned.files.every((file) => file.status === "create")).toBe(true);
    await expect(access(path.join(root, ".moye"))).rejects.toMatchObject({ code: "ENOENT" });

    const applied = await applyStandardDocumentationScaffold(root, { projectId: "blank-project" });
    expect(applied.applied).toBe(true);
    expect(applied.created).toHaveLength(applied.files.length);
    expect(applied.files.every((file) => file.status === "unchanged")).toBe(true);
    const loaded = await loadProjectManifest(path.join(root, ".moye", "project.yaml"));
    expect(loaded.manifest.documentation).toEqual({
      policy: "custom",
      command: { id: "standard-docs-validate", argv: ["node", "scripts/docs_validate.mjs"], cwd: "." },
    });
    const validation = JSON.parse((await execFileAsync(process.execPath, ["scripts/docs_validate.mjs"], { cwd: root })).stdout) as { valid: boolean; scaffoldDigest: string };
    expect(validation).toEqual(expect.objectContaining({ valid: true, scaffoldDigest: applied.scaffoldDigest }));

    const repeated = await applyStandardDocumentationScaffold(root, { projectId: "blank-project" });
    expect(repeated.applied).toBe(true);
    expect(repeated.created).toEqual([]);
    expect(repeated.unchanged).toHaveLength(repeated.files.length);
    expect(repeated.scaffoldDigest).toBe(applied.scaffoldDigest);

    const manifestPath = path.join(root, ".moye", "project.yaml");
    const customized = JSON.parse(await readFile(manifestPath, "utf8")) as { tests: unknown };
    customized.tests = [{ id: "project-test", argv: ["node", "--test"], cwd: "." }];
    await writeFile(manifestPath, `${JSON.stringify(customized, null, 2)}\n`);
    await expect(loadProjectManifest(manifestPath)).resolves.toMatchObject({ manifest: { tests: [{ id: "project-test" }] } });
    await expect(execFileAsync(process.execPath, ["scripts/docs_validate.mjs"], { cwd: root })).resolves.toMatchObject({ stdout: expect.stringContaining('"valid":true') });
  });

  it("reports every pre-existing content conflict before writing anything", async () => {
    const root = await gitFixture("occupied-project");
    await writeFile(path.join(root, "README.md"), "# Existing product\n");
    await mkdir(path.join(root, "docs"));
    await writeFile(path.join(root, "docs", "README.md"), "# Existing docs\n");

    const result = await applyStandardDocumentationScaffold(root, { projectId: "occupied-project" });
    expect(result.applied).toBe(false);
    expect(result.conflicts.map((item) => item.path)).toEqual(["README.md", "docs/README.md"]);
    expect(await readFile(path.join(root, "README.md"), "utf8")).toBe("# Existing product\n");
    await expect(access(path.join(root, "AGENTS.md"))).rejects.toMatchObject({ code: "ENOENT" });
    await expect(access(path.join(root, ".moye"))).rejects.toMatchObject({ code: "ENOENT" });
  });

  it("never follows a symlinked scaffold parent", async () => {
    const root = await gitFixture("symlink-project");
    const outside = await mkdtemp(path.join(os.tmpdir(), "moye-docs-scaffold-outside-"));
    fixtures.push(outside);
    await symlink(outside, path.join(root, "docs"));
    const result = await applyStandardDocumentationScaffold(root, { projectId: "symlink-project" });
    expect(result.applied).toBe(false);
    expect(result.conflicts.some((item) => item.conflictCode === "SYMLINK")).toBe(true);
    expect(await collect(outside)).toEqual([]);
  });

  it("does not repair modified generated bytes or accept implicit template migration", async () => {
    const root = await gitFixture("drift-project");
    await applyStandardDocumentationScaffold(root, { projectId: "drift-project" });
    await writeFile(path.join(root, "AGENTS.md"), "user-owned replacement\n");
    const drift = await applyStandardDocumentationScaffold(root, { projectId: "drift-project" });
    expect(drift.applied).toBe(false);
    expect(drift.conflicts).toEqual([expect.objectContaining({ path: "AGENTS.md", conflictCode: "CONTENT_DIFFERS" })]);
    expect(await readFile(path.join(root, "AGENTS.md"), "utf8")).toBe("user-owned replacement\n");
    await expect(planStandardDocumentationScaffold(root, { templateVersion: "standard-docs-v2" })).rejects.toMatchObject({ code: "SCAFFOLD_TEMPLATE_VERSION_UNSUPPORTED" });
  });

  it("deterministically blocks a Candidate that changes product code without project facts", async () => {
    const root = await gitFixture("policy-project");
    await applyStandardDocumentationScaffold(root, { projectId: "policy-project" });
    await execFileAsync("git", ["-C", root, "add", "."]);
    await execFileAsync("git", ["-C", root, "-c", "user.name=Moye Test", "-c", "user.email=test@moye.local", "commit", "-qm", "base"]);
    const base = (await execFileAsync("git", ["-C", root, "rev-parse", "HEAD"])).stdout.trim();
    await mkdir(path.join(root, "src"));
    await writeFile(path.join(root, "src", "value.ts"), "export const value = 2;\n");
    await execFileAsync("git", ["-C", root, "add", "."]);
    await execFileAsync("git", ["-C", root, "-c", "user.name=Moye Test", "-c", "user.email=test@moye.local", "commit", "-qm", "code only"]);
    const codeOnly = (await execFileAsync("git", ["-C", root, "rev-parse", "HEAD"])).stdout.trim();
    const policyEnv = { ...process.env, MOYE_DOCUMENTATION_BASE_COMMIT: base, MOYE_DOCUMENTATION_CANDIDATE_COMMIT: codeOnly };
    await expect(execFileAsync(process.execPath, ["scripts/docs_validate.mjs"], { cwd: root, env: policyEnv, encoding: "utf8" })).rejects.toMatchObject({ stderr: expect.stringContaining("SCAFFOLD_DOC_CHANGE_REQUIRED") });

    await writeFile(path.join(root, "docs", "knowledge", "product.md"), "# Product facts\n\nValue is 2.\n");
    await execFileAsync("git", ["-C", root, "add", "."]);
    await execFileAsync("git", ["-C", root, "-c", "user.name=Moye Test", "-c", "user.email=test@moye.local", "commit", "-qm", "document product fact"]);
    const documented = (await execFileAsync("git", ["-C", root, "rev-parse", "HEAD"])).stdout.trim();
    await expect(execFileAsync(process.execPath, ["scripts/docs_validate.mjs"], { cwd: root, env: { ...process.env, MOYE_DOCUMENTATION_BASE_COMMIT: base, MOYE_DOCUMENTATION_CANDIDATE_COMMIT: documented }, encoding: "utf8" })).resolves.toMatchObject({ stdout: expect.stringContaining('"valid":true') });
  });

  it("requires the exact physical Git root", async () => {
    const plain = await mkdtemp(path.join(os.tmpdir(), "moye-docs-scaffold-plain-"));
    fixtures.push(plain);
    await expect(planStandardDocumentationScaffold(plain)).rejects.toMatchObject({ code: "SCAFFOLD_GIT_REPOSITORY_REQUIRED" });

    const root = await gitFixture("root-project");
    const child = path.join(root, "child");
    await mkdir(child);
    await expect(planStandardDocumentationScaffold(child)).rejects.toMatchObject({ code: "SCAFFOLD_PROJECT_ROOT_REQUIRED" });
  });

  it("converges concurrent identical apply calls without overwriting", async () => {
    const root = await gitFixture("concurrent-project");
    const [first, second] = await Promise.all([
      applyStandardDocumentationScaffold(root, { projectId: "concurrent-project" }),
      applyStandardDocumentationScaffold(root, { projectId: "concurrent-project" }),
    ]);
    expect(first.applied).toBe(true);
    expect(second.applied).toBe(true);
    expect(first.scaffoldDigest).toBe(second.scaffoldDigest);
    expect(first.files.every((file) => file.status === "unchanged")).toBe(true);
    expect(second.files.every((file) => file.status === "unchanged")).toBe(true);
    await expect(execFileAsync(process.execPath, ["scripts/docs_validate.mjs"], { cwd: root })).resolves.toMatchObject({ stdout: expect.stringContaining('"valid":true') });
  });
});

async function gitFixture(name: string): Promise<string> {
  const parent = await mkdtemp(path.join(os.tmpdir(), "moye-docs-scaffold-"));
  fixtures.push(parent);
  const root = path.join(parent, name);
  await mkdir(root);
  await execFileAsync("git", ["init", "-q", "-b", "main"], { cwd: root });
  return root;
}

async function collect(directory: string): Promise<string[]> {
  const { readdir } = await import("node:fs/promises");
  return (await readdir(directory)).sort();
}
